Core service
WingsDao/griffin-consensus-poc pull request #30
Opened 2019-04-08 13:39 UTC by borispovod

Still draft, as still have to implement block producers function and improve tests.

2019-04-08 19:50 UTC, romfrolov commented on core/chain.js
> + * Returns balance of account.
For return value there is **@return** (or **@returns** tag) in jsdoc. It's a good practice to describe what function does in a more generic way.

2019-04-08 19:50 UTC, romfrolov commented on core/chain.js
> + * Returns stake of account.
See [comment above](https://github.com/WingsDao/griffin-consensus-poc/pull/30/files?file-filters%5B%5D=.js&file-filters%5B%5D=.json#r273210628).

2019-04-08 19:50 UTC, romfrolov commented on core/chain.js
> + * Returns votes for account.
See [comment above](https://github.com/WingsDao/griffin-consensus-poc/pull/30/files?file-filters%5B%5D=.js&file-filters%5B%5D=.json#r273210628).

2019-04-08 19:52 UTC, romfrolov commented on core/chain.js
> + * Returns account by address from latetst block.
See [comment above](https://github.com/WingsDao/griffin-consensus-poc/pull/30/files?file-filters%5B%5D=.js&file-filters%5B%5D=.json#r273210628).

2019-04-08 19:54 UTC, romfrolov commented on genesis.json
> +    "state": []
Please, check [genesis library](https://github.com/WingsDao/griffin-consensus-poc/blob/delegates/lib/genesis.js#L31-L38) for compatibility with this change.

2019-04-08 19:56 UTC, romfrolov commented on test/unit/chain.js
> +        console.log('Balance: ', balance);
If you are passing arguments using comma separation extra space will be added automatically.
```suggestion
        console.log('Balance:', balance);
```

2019-04-08 19:56 UTC, romfrolov commented on test/unit/chain.js
> +        console.log('Stake: ', stake);
```suggestion
        console.log('Stake:', stake);
```

2019-04-08 19:56 UTC, romfrolov commented on test/unit/chain.js
> +        console.log('Votes: ', votes);
```suggestion
        console.log('Votes:', votes);
```

2019-04-08 19:56 UTC, romfrolov commented on test/unit/chain.js
> +        console.log('Delegates: ', delegates);
```suggestion
        console.log('Delegates:', delegates);
```

2019-04-08 19:56 UTC, romfrolov commented on test/unit/chain.js
> +        console.log('Active delegates: ', activeDelegates);
```suggestion
        console.log('Active delegates:', activeDelegates);
```

2019-04-08 19:56 UTC, romfrolov commented on test/unit/chain.js
> +        console.log('Successor delegates', successorDelegates);
```suggestion
        console.log('Successor delegates:', successorDelegates);
```

2019-04-08 19:57 UTC, romfrolov commented on test/unit/chain.js
> +    it('get delegatets count', async () => {
```suggestion
    it('get delegates count', async () => {
```

2019-04-08 19:58 UTC, romfrolov commented on test/unit/chain.js
> +const chain = require('core/chain');
```suggestion
const chain   = require('core/chain');
```

2019-04-08 20:01 UTC, romfrolov commented on test/unit/chain.js
> +    Buffer.from('557dce58018cf502a32b9b7723024805399350d006a4f71c3b9f489f7085cb50', 'hex'),
What is the reason for hard-coded secret keys? If no secret key is provided, random secret key will be generated on each account creation (see [core/account.js](https://github.com/WingsDao/griffin-consensus-poc/blob/delegates/core/account.js#L34-L36)).

2019-04-08 20:02 UTC, romfrolov submitted a review, later dismissed
Please see comments to resolve issues.

2019-04-09 08:54 UTC, damirka commented on core/account.js
> +Account.prototype.getStrAddress = function getStrAddress() {
It's probably should be called 'getAddressHex' or 'getHexAddress'. Buffer can be transformed to string in a numerous ways, so calling it 'str' is not the best way of describing what this function does.

2019-04-09 08:58 UTC, damirka submitted a review, later dismissed

2019-04-09 08:58 UTC, damirka commented on test/unit/chain.js
> +});
New line in the end of file is obligatory.

2019-04-09 23:40 UTC, borispovod commented
Need to clarify difference between blockchain.js functional and chain.js functional and probably merge them

2019-04-15 09:51 UTC, damirka requested changes

2019-04-15 09:51 UTC, damirka commented on core/blockchain.js
> +    return delegates.slice(0, 31);
31 is a magic number.
It has to be defined as module-level constant and exported outside.
i.e.
```JavaScript
const ACTIVE_DELEGATES_COUNT = exports.ACTIVE_DELEGATES_COUNT = 31;
```

2019-04-15 09:51 UTC, damirka commented on core/blockchain.js
> +    const delegates = await this.getDelegates();
It's better not to use 'this' context with static methods. 
You can define `getDelegates` as a function, export it and use in methods like this.

2019-04-15 09:51 UTC, damirka commented on core/blockchain.js
> +}
Empty line required.

2019-04-15 09:51 UTC, damirka commented on core/account.js
> +Account.prototype.getHexAddress = function getHexAddress() {
👍🏻👍🏻👍🏻

2019-04-15 12:25 UTC, damirka approved these changes

2019-04-15 12:25 UTC, merged