Added bank client and event to request coin
WingsDao/griffin-consensus-poc pull request #31
Opened 2019-04-10 11:25 UTC by damirka

To provide interactivity we need some coin to start. 
Emit `events.GIMME_COIN` and send there your address to receive some in next block.

Of course some REPL we're gonna implement will have this functionality by default.

2019-04-10 20:16 UTC, romfrolov commented on runner.js
> +const bankKiddo = cp.fork('clients/bank.js', ['bank'], {env: Object.assign(env, {SECRET_KEY: bank.secretKey.toString('hex')})});
What does `bankKiddo` stand for?

2019-04-10 20:18 UTC, romfrolov commented on clients/bank.js
> +    tp.send(evt.NEW_TRANSACTION, acc.tx('0x' + addr, AMOUNT));
Correct me if I'm wrong, but if address is string it should already have `0x` prefix.

2019-04-10 23:05 UTC, damirka commented on clients/bank.js
> +    tp.send(evt.NEW_TRANSACTION, acc.tx('0x' + addr, AMOUNT));
It's not normalised. There should either be a single method defining an 'address' as it should be or the shortest/simplest version possible. And now and in [other pr](https://github.com/WingsDao/griffin-consensus-poc/pull/32) shortest method is this one.

Of course there's an obvious caveat with sending '0x' prefixed transactions which must be solved as well.

2019-04-15 17:31 UTC, borispovod requested changes

2019-04-15 17:31 UTC, borispovod commented on clients/bank.js
> +    tp.send(evt.NEW_TRANSACTION, acc.tx('0x' + addr, AMOUNT));
I can agree with Roma, address in case of string representation must have '0x' as prefix, or it could be bytes array, not a string.

2019-04-15 17:31 UTC, borispovod commented on runner.js
> +genesis.addAccount(bank.address.toString('hex'), 1000000);
Look at changes in core/account https://github.com/WingsDao/griffin-consensus-poc/pull/11/commits/ba63d99a5dc8232ee66ebd7d13e3f60682098e0a#diff-9d53720ebbf552f679e0fd32f4094f9fR87 , you can use new method to get address in string representation.

2019-04-19 09:44 UTC, damirka commented on runner.js
> +genesis.addAccount(bank.address.toString('hex'), 1000000);
Nope. I can't. Genesis doesn't support 0x-prefixed addresses.

2019-04-19 09:48 UTC, merged